### ISSUE TITLE
Platform instances do not call overridden ApplyVariant methods on build

### ISSUE THREAD

**Issue by robinnorth** [superunitybuild/buildtool#62]
This is due to platform objects being cast to `BuildPlatform` on serializing. Currently, only Android and iOS platforms make use of this feature.

I believe a possible fix may be to create an `IBuildPlatform` interface for platforms to derive from and converting the serialized array of platforms to use this, rather than force its contents to be cast to `BuildPlatform`.

**Comment by robinnorth** [comment]
`BuildAction`s appear to work in the way that `BuildPlatform`s should (i.e. they are covariant when deserialized and their overridden methods are called correctly when build actions are processed), so the differences between the way these two types are serialized could be investigated. 

This seems to be the key:

https://github.com/Chaser324/unity-build/blob/63270fc8830a22d877c99c1d8a7238f7ea517c75/Editor/Build/Action/UI/BuildActionListDrawer.cs#L170-L177

**Comment by nickfourtimes** [comment]
I came across this exact issue yesterday, and was about to file an issue – great timing.

I was able to temporarily work around the problem in here:
https://github.com/Chaser324/unity-build/blob/63270fc883/Editor/Build/Platform/UI/BuildPlatformListDrawer.cs#L67-L77

Basically, I had to change the Add() line from:
`platformList.platforms.Add((BuildPlatform)Activator.CreateInstance(availablePlatformTypeList[index]));`
to:
`platformList.platforms.Add(Activator.CreateInstance(availablePlatformTypeList[index]) as BuildPlatform);`

There's a subtle difference between `(SomeType)myObject` and `myObject as SomeType` which is causing the problem. The only issue with this workaround is that as I mentioned it's temporary: in my case, I had to remove the platforms from the platform list, add them back again, and then run a build. On that build, the overridden `ApplyVariant()` was called in my custom build platform, rather than the virtual one in BuildPlatform. However, once I restarted the Unity editor, it went back to calling the virtual, top-level `ApplyVariant()` rather than my custom one.

I think the ultimate solution will be as you say, to make an interface that all BuildPlatforms can inherit from.

**Comment by robinnorth** [comment]
@nickfourtimes thanks for adding your findings. I had also noticed that you could delete a platform, recreate it and have the child `ApplyVariant` called in the same Unity Editor session, only to have it revert to the previous broken behaviour upon restarting the Editor, but I was able to do this _without_ changing the way the type of the created platform instance was cast.

In any case though, it's the way in which these instances are serialized to the Unity Build settings asset that is the issue, as confirmed by this behaviour. I do think the solution might actually just require converting the way platform instances are created and serialized to match the way `BuildActions` are handled. Specifically, the use of `ScriptableObject.CreateInstance` rather than `Activator.CreateInstance` to instantiate and then `AssetDatabase.AddObjectToAsset` and `AssetDatabase.ImportAsset` to serialize.

If you inspect `Assets/UnityBuildSettings/UnityBuildSettings.asset` in a text editor, you'll notice that these different approaches result in different data being serialized:

For an instance of the `BuildAndroid` platform:

```yaml
- enabled: 1
  distributionList:
distributions: []
  architectures:
  - target: 13
name: Android
enabled: 1
binaryNameFormat: '{0}.apk'
  variants:
  - variantName: Device Type
selectedIndex: 2
values:
- ARMv7
- ARM64
- All
  - variantName: Texture Compression
selectedIndex: 2
values:
- ETC
- ETC2
- ASTC
- DXT
- PVRTC
- ATC
- Generic
  - variantName: Build System
selectedIndex: 1
values:
- Internal
- Gradle
- ADT (Legacy)
  - variantName: Split APKs
selectedIndex: 1
values:
- Disabled
- Enabled
  platformName: Android
  dataDirNameFormat: '{0}_Data'
  targetGroup: 7
```

compared to an instance of the `FileOperation` build action:

```
--- !u!114 &-5861510407077859309
MonoBehaviour:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_GameObject: {fileID: 0}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 11500000, guid: 86e19aa5315bf4a409c07e84ca8c4248, type: 3}
  m_Name: FileOperation
  m_EditorClassIdentifier: 
  actionType: 1
  actionName: FileOperation
  note: VR Client (Android)
  actionEnabled: 1
  filter:
    condition: 2
    clauses:
    - type: 0
      comparison: 0
      test: VR CLIENT
    - type: 1
      comparison: 0
      test: ANDROID
  inputPath: Assets\__APP\Plugins\VR Client\Android\AndroidManifest.xml
  outputPath: Assets\Plugins\Android\AndroidManifest.xml
  recursiveSearch: 1
  operation: 1
```

Specifically, the latter is serialized as a `MonoBehaviour` instance with a `m_Script` property that allows Unity to instantiate the correct child class on deserializing the settings asset. If platform instances were handled the same way, `ApplyVariant` inheritance should work as expected and survive Editor restarts, I believe.

It's on my to-do list to fix this at some point, but I'm currently busy finishing off a project, so haven't had time to test out the above just yet!
